---
apiVersion: v1
kind: Service
metadata:
   name: {{ .Chart.Name }}
   labels:
     app: {{ .Chart.Name }}
   namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }} 
